### ISSUE TITLE
Add data of Montreal's bicycle tracks

### ISSUE THREAD

**Issue by BCSharp** [ipython-books/cookbook-data#2]
In Recipe 1.2, [cookbook-code](https://github.com/ipython-books/cookbook-code) uses currently data from a URL that is not available anymore.

However, data from [another location](http://donnees.ville.montreal.qc.ca/dataset/f170fecc-18db-44bc-b4fe-5b0b6d2c7297/resource/ec12447d-6b2a-45d0-b0e7-fd69c382e368/download/2013.csv) does work with that Recipe.

I propose to add the dataset here, and modify the recipe to use a GitHub-hosted URL. Add the dataset preferably in the csv rather than zip format as pandas cannot decompress zip files on the fly (zip files are multi-file containers). pandas can, however, decompress gzip (file extension .gz) and bzip2 (file extension .bz2) files, so one of those compression schemes may be used, if compression is needed at all.

**Comment by rossant** [comment]
:+1: to add the raw 15KB csv file (no need to compress I think)
